name: Bug Report
description: Create a bug report for the Admin Project
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did not work
      description: Please describe exactly what you saw that was unexpected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduce
      description: Steps to reproduce the behavior. Screenshots can be provided.
      placeholder: 1. Go to '...' 2. Click on '....' 3.Scroll down to '....' 4. See error
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Brave
        - Opera
        - Safari
        - Microsoft Edge
    validations:
      required: true
